<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TKK5GPG" name="LoginTest" tests="2" failures="1" timestamp="5 Feb 2021 14:21:06 GMT" time="121.726" errors="0">
  <testcase name="testA1" time="0.043" classname="com.qtpselenium.core.ddf.zohotestcases.LoginTest">
    <skipped/>
  </testcase> <!-- testA1 -->
  <testcase name="testA1" time="119.707" classname="com.qtpselenium.core.ddf.zohotestcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Login test has failed">
      <![CDATA[java.lang.AssertionError: Login test has failed
	at com.qtpseleniun.core.ddf.base.BaseTest.reportFailure(BaseTest.java:187)
	at com.qtpseleniun.core.ddf.base.BaseTest.login(BaseTest.java:223)
	at com.qtpselenium.core.ddf.zohotestcases.LoginTest.testA1(LoginTest.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testA1 -->
</testsuite> <!-- LoginTest -->
